language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
    - sudo apt-get -y install automake gcc make libopenal-dev libopenscenegraph-dev libsndfile1-dev libwxgtk3.0-dev libboost-dev
    
script:
  - bash cmake -DCMAKE_BUILD_TYPE=Debug -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-gtk3 .
  - make
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
  - chmod a+x upload.sh
  - bash ./upload.sh ./binaural-audio-editor*.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
